-- ============================================================
-- MOMENTUM — Batch 6 : PPL Focus (4 variantes)
-- Mêmes principes Antonin appliqués au format PPL rotation
-- ============================================================